### ISSUE TITLE
Payment Overview Payment options

### ISSUE THREAD

**Issue by dpeck1** [emooretc/irs-account-prototype#5]
even though payment overview and payment options are static content can we still have them have the same accordion functionality

**Comment by emooretc** [comment]
We certainly can.  I wasn't sure what the "summary" data would be that would be shown when the accordion is closed.  All the others have some high level data and then the accordion provides some additional details. I thought it might be weird to have the grid box have no real content in it when the accordion is closed.  Let me know how you are envisioning seeing that.

**Comment by dpeck1** [comment]
On those I would just show the header then the expand and see the table on payments and the actual options for payment on make a payment.

Thanks,

Darren A Peck
Business Process Manager
IRS | ICCE Program
W: (469) 801-0142
C  : (214) 417-2004
darren.a.peck@leidos.com
darren.peck@irs.gov<mailto:Darren.peck@irs.gov>
[cid:image001.png@01D21FB4.5D9759A0]

**Comment by emooretc** [comment]
Take a look.
