### ISSUE TITLE
My Bal Due

### ISSUE THREAD

**Issue by dpeck1** [emooretc/irs-account-prototype#6]
can we get the dollar amounts in the overview table right justified

**Comment by emooretc** [comment]
Take a look, I left justified them so they would line up with the header.  When I right justified it looked weird with the header being left justified.  Let me know what you think.

**Comment by dpeck1** [comment]
Looks good



Thanks,

Darren A Peck
Business Process Manager
IRS | ICCE Program
W: (469) 801-0142
C  : (214) 417-2004
darren.a.peck@leidos.com
darren.peck@irs.gov<mailto:Darren.peck@irs.gov>
[cid:image001.png@01D21FB4.24AC9470]
